name: 'Chromatic'
on: push
env:
  NODE_ENV: test
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm i --legacy-peer-deps && npm run build-storybook
      - name: Publish to non-master non-beta to Chromatic
        if: github.ref != 'refs/heads/master' && github.ref != 'refs/heads/beta'
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        env:
          STORYBOOK_BUILD_TIMEOUT: 1200000
          NODE_ENV: test
          CI: true
      - name: Publish Chromatic and auto accept changes for master and beta
        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/beta'
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: true # 👈 Option to accept all changes
        env:
          STORYBOOK_BUILD_TIMEOUT: 1200000
          NODE_ENV: test
          CI: true
